### ISSUE TITLE
Выбор алгоритма

### ISSUE THREAD

**Issue by GlNaumov** [KapikPro/project#1]
Необходимо до !!!8.04.2022!!! определиться с алгоритмом, который мы будем делать. Право выбора у дизайнера с разработчиком.

**Comment by KapikPro** [comment]
Я предлагаю выбрать алгоритм "поиск элемента в одномерном массиве" или "сортировка одномерного массива", потому он имеет много способов реализации и очень удобен для тестирования.

**Comment by tearnes** [comment]
Думаю, что действительно стоит выбрать между этими двумя алгоритмами. Склоняюсь больше к "поиск элемента в одномерном массиве", так как считаю его более интересным в плане работы с ним

**Comment by KapikPro** [comment]
> Думаю, что действительно стоит выбрать между этими двумя алгоритмами. Склоняюсь больше к "поиск элемента в одномерном массиве", так как считаю его более интересным в плане работы с ним

пожалуй, соглашусь с тобой, возьмём этот алгоритм
