### ISSUE TITLE
Разработка до 29.04.2022

### ISSUE THREAD

**Issue by GlNaumov** [KapikPro/project#3]
Далее начинаем разработку самой программы, на это тоже даётся 2 недели ( до 29.04.2022) Параллельно разработке некоторые части можно отдельно отдавать тестировать, чтобы ускорить процесс и выявить большинство багов сразу.

**Comment by KapikPro** [comment]
- [x] выбрать способы реализации алгоритма, которые мы будем исследовать

- [x] приступить к их разработке

- [x] отдать тестировщику готовую программу

- [x] внести правки при необходимости

- [x] отдать готовую к исследованию программу аналитику
